 Tue, 11 Jun 2019 20:04:34  INFO test_api.py test_api [ line:23 ] 正在执行第1条用例
 Tue, 11 Jun 2019 20:04:34  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 1, 'func': 'register', 'describe': '注册成功-昵称为空', 'method': 'post', 'apiName': '/member/register', 'param': "{'mobilephone':'${tel}','pwd':'123456','regname':''}", 'expected': 10001}
 Tue, 11 Jun 2019 20:04:34  INFO http_request.py http_request [ line:21 ] 发起post请求
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:35  ERROR test_api.py test_api [ line:35 ] 断言出错啦，期望结果为：10001，实际结果为：20109
Traceback (most recent call last):
  File "E:\test study\project_2\QCD_API\test_case\test_api.py", line 32, in test_api
    self.assertEqual(eval(res.json()['code']),args['expected'])
  File "D:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "D:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 20109 != 10001
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:23 ] 正在执行第2条用例
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 2, 'func': 'register', 'describe': '注册成功-昵称不为空', 'method': 'post', 'apiName': '/member/register', 'param': "{'mobilephone':'13311111111','pwd':'123456','regname':'呵呵哒'}", 'expected': 10001}
 Tue, 11 Jun 2019 20:04:35  INFO http_request.py http_request [ line:21 ] 发起post请求
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': '20110', 'data': None, 'msg': '手机号码已被注册'}
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:35  ERROR test_api.py test_api [ line:35 ] 断言出错啦，期望结果为：10001，实际结果为：20110
Traceback (most recent call last):
  File "E:\test study\project_2\QCD_API\test_case\test_api.py", line 32, in test_api
    self.assertEqual(eval(res.json()['code']),args['expected'])
  File "D:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "D:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 20110 != 10001
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:23 ] 正在执行第3条用例
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 3, 'func': 'register', 'describe': '手机号已被注册', 'method': 'get', 'apiName': '/member/register', 'param': "{'mobilephone':'13311111111','pwd':'123456','regname':''}", 'expected': 20110}
 Tue, 11 Jun 2019 20:04:35  INFO http_request.py http_request [ line:14 ] 发起get请求
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': '20110', 'data': None, 'msg': '手机号码已被注册'}
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:23 ] 正在执行第4条用例
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 4, 'func': 'register', 'describe': '注册密码为空', 'method': 'post', 'apiName': '/member/register', 'param': "{'mobilephone':'13311111110','pwd':'','regname':''}", 'expected': 20103}
 Tue, 11 Jun 2019 20:04:35  INFO http_request.py http_request [ line:21 ] 发起post请求
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': '20103', 'data': None, 'msg': '密码不能为空'}
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:23 ] 正在执行第5条用例
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 5, 'func': 'register', 'describe': '注册手机号为空', 'method': 'get', 'apiName': '/member/register', 'param': "{'mobilephone':'','pwd':'123456','regname':''}", 'expected': 20103}
 Tue, 11 Jun 2019 20:04:35  INFO http_request.py http_request [ line:14 ] 发起get请求
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': '20103', 'data': None, 'msg': '手机号不能为空'}
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:23 ] 正在执行第6条用例
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 6, 'func': 'register', 'describe': '密码长度小于6位', 'method': 'post', 'apiName': '/member/register', 'param': "{'mobilephone':'13311111110','pwd':'12345','regname':''}", 'expected': 20108}
 Tue, 11 Jun 2019 20:04:35  INFO http_request.py http_request [ line:21 ] 发起post请求
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': '20108', 'data': None, 'msg': '密码长度必须为6~18'}
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:23 ] 正在执行第7条用例
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 7, 'func': 'register', 'describe': '密码长度大于18位', 'method': 'post', 'apiName': '/member/register', 'param': "{'mobilephone':'13311111110','pwd':'1234567890123456789','regname':''}", 'expected': 20108}
 Tue, 11 Jun 2019 20:04:35  INFO http_request.py http_request [ line:21 ] 发起post请求
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': '20108', 'data': None, 'msg': '密码长度必须为6~18'}
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:23 ] 正在执行第8条用例
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 8, 'func': 'register', 'describe': '手机号格式不正确', 'method': 'post', 'apiName': '/member/register', 'param': "{'mobilephone':'13301','pwd':'123456','regname':''}", 'expected': 20109}
 Tue, 11 Jun 2019 20:04:35  INFO http_request.py http_request [ line:21 ] 发起post请求
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': '20109', 'data': None, 'msg': '手机号码格式不正确'}
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:23 ] 正在执行第9条用例
 Tue, 11 Jun 2019 20:04:35  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 9, 'func': 'login', 'describe': '登录成功', 'method': 'post', 'apiName': '/member/login', 'param': "{'mobilephone':'13311111111','pwd':'123456'}", 'expected': 10001}
 Tue, 11 Jun 2019 20:04:35  INFO http_request.py http_request [ line:21 ] 发起post请求
 Tue, 11 Jun 2019 20:04:36  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 1, 'code': '10001', 'data': None, 'msg': '登录成功'}
 Tue, 11 Jun 2019 20:04:36  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:36  INFO test_api.py test_api [ line:23 ] 正在执行第10条用例
 Tue, 11 Jun 2019 20:04:36  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 10, 'func': 'login', 'describe': '手机号为空', 'method': 'post', 'apiName': '/member/login', 'param': "{'mobilephone':'','pwd':'123456'}", 'expected': 20103}
 Tue, 11 Jun 2019 20:04:36  INFO http_request.py http_request [ line:21 ] 发起post请求
 Tue, 11 Jun 2019 20:04:36  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': '20103', 'data': None, 'msg': '手机号不能为空'}
 Tue, 11 Jun 2019 20:04:36  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:36  INFO test_api.py test_api [ line:23 ] 正在执行第11条用例
 Tue, 11 Jun 2019 20:04:36  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 11, 'func': 'login', 'describe': '密码为空', 'method': 'post', 'apiName': '/member/login', 'param': "{'mobilephone':'13311111111','pwd':''}", 'expected': 20103}
 Tue, 11 Jun 2019 20:04:36  INFO http_request.py http_request [ line:21 ] 发起post请求
 Tue, 11 Jun 2019 20:04:36  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': '20103', 'data': None, 'msg': '密码不能为空'}
 Tue, 11 Jun 2019 20:04:36  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:36  INFO test_api.py test_api [ line:23 ] 正在执行第12条用例
 Tue, 11 Jun 2019 20:04:36  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 12, 'func': 'login', 'describe': '输入手机号为未注册的手机号', 'method': 'post', 'apiName': '/member/login', 'param': "{'mobilephone':'13311111100','pwd':'123456'}", 'expected': 20111}
 Tue, 11 Jun 2019 20:04:36  INFO http_request.py http_request [ line:21 ] 发起post请求
 Tue, 11 Jun 2019 20:04:36  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': '20111', 'data': None, 'msg': '用户名或密码错误'}
 Tue, 11 Jun 2019 20:04:36  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:36  INFO test_api.py test_api [ line:23 ] 正在执行第13条用例
 Tue, 11 Jun 2019 20:04:36  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 13, 'func': 'login', 'describe': '输入的密码错误', 'method': 'post', 'apiName': '/member/login', 'param': "{'mobilephone':'13311111111','pwd':'123'}", 'expected': 20111}
 Tue, 11 Jun 2019 20:04:36  INFO http_request.py http_request [ line:21 ] 发起post请求
 Tue, 11 Jun 2019 20:04:36  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': '20111', 'data': None, 'msg': '用户名或密码错误'}
 Tue, 11 Jun 2019 20:04:36  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:36  INFO test_api.py test_api [ line:23 ] 正在执行第14条用例
 Tue, 11 Jun 2019 20:04:36  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 14, 'func': 'recharge', 'describe': '充值成功', 'method': 'get', 'apiName': '/member/recharge', 'param': "{'mobilephone':'13311111111','amount':'5000'}", 'expected': 10001}
 Tue, 11 Jun 2019 20:04:36  INFO http_request.py http_request [ line:14 ] 发起get请求
 Tue, 11 Jun 2019 20:04:36  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': None, 'data': None, 'msg': '抱歉，请先登录。'}
 Tue, 11 Jun 2019 20:04:36  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:36  ERROR test_api.py test_api [ line:35 ] 断言出错啦，期望结果为：10001，实际结果为：None
Traceback (most recent call last):
  File "E:\test study\project_2\QCD_API\test_case\test_api.py", line 32, in test_api
    self.assertEqual(eval(res.json()['code']),args['expected'])
TypeError: eval() arg 1 must be a string, bytes or code object
 Tue, 11 Jun 2019 20:04:36  INFO test_api.py test_api [ line:23 ] 正在执行第15条用例
 Tue, 11 Jun 2019 20:04:36  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 15, 'func': 'recharge', 'describe': '充值时未输入金额', 'method': 'post', 'apiName': '/member/recharge', 'param': "{'mobilephone':'13311111111','amount':''}", 'expected': 20115}
 Tue, 11 Jun 2019 20:04:36  INFO http_request.py http_request [ line:21 ] 发起post请求
 Tue, 11 Jun 2019 20:04:37  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': None, 'data': None, 'msg': '抱歉，请先登录。'}
 Tue, 11 Jun 2019 20:04:37  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:37  ERROR test_api.py test_api [ line:35 ] 断言出错啦，期望结果为：20115，实际结果为：None
Traceback (most recent call last):
  File "E:\test study\project_2\QCD_API\test_case\test_api.py", line 32, in test_api
    self.assertEqual(eval(res.json()['code']),args['expected'])
TypeError: eval() arg 1 must be a string, bytes or code object
 Tue, 11 Jun 2019 20:04:37  INFO test_api.py test_api [ line:23 ] 正在执行第16条用例
 Tue, 11 Jun 2019 20:04:37  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 16, 'func': 'recharge', 'describe': '不输入手机号', 'method': 'post', 'apiName': '/member/recharge', 'param': "{'mobilephone':'','amount':'5000'}", 'expected': 20103}
 Tue, 11 Jun 2019 20:04:37  INFO http_request.py http_request [ line:21 ] 发起post请求
 Tue, 11 Jun 2019 20:04:37  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': None, 'data': None, 'msg': '抱歉，请先登录。'}
 Tue, 11 Jun 2019 20:04:37  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:37  ERROR test_api.py test_api [ line:35 ] 断言出错啦，期望结果为：20103，实际结果为：None
Traceback (most recent call last):
  File "E:\test study\project_2\QCD_API\test_case\test_api.py", line 32, in test_api
    self.assertEqual(eval(res.json()['code']),args['expected'])
TypeError: eval() arg 1 must be a string, bytes or code object
 Tue, 11 Jun 2019 20:04:37  INFO test_api.py test_api [ line:23 ] 正在执行第17条用例
 Tue, 11 Jun 2019 20:04:37  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 17, 'func': 'recharge', 'describe': '不存在的会员手机账号', 'method': 'post', 'apiName': '/member/recharge', 'param': "{'mobilephone':'13322111111','amount':'5000'}", 'expected': 20104}
 Tue, 11 Jun 2019 20:04:37  INFO http_request.py http_request [ line:21 ] 发起post请求
 Tue, 11 Jun 2019 20:04:37  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': None, 'data': None, 'msg': '抱歉，请先登录。'}
 Tue, 11 Jun 2019 20:04:37  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:37  ERROR test_api.py test_api [ line:35 ] 断言出错啦，期望结果为：20104，实际结果为：None
Traceback (most recent call last):
  File "E:\test study\project_2\QCD_API\test_case\test_api.py", line 32, in test_api
    self.assertEqual(eval(res.json()['code']),args['expected'])
TypeError: eval() arg 1 must be a string, bytes or code object
 Tue, 11 Jun 2019 20:04:37  INFO test_api.py test_api [ line:23 ] 正在执行第18条用例
 Tue, 11 Jun 2019 20:04:37  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 18, 'func': 'recharge', 'describe': '手机格式不正确', 'method': 'post', 'apiName': '/member/recharge', 'param': "{'mobilephone':'1331111','amount':'5000'}", 'expected': 20109}
 Tue, 11 Jun 2019 20:04:37  INFO http_request.py http_request [ line:21 ] 发起post请求
 Tue, 11 Jun 2019 20:04:37  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': None, 'data': None, 'msg': '抱歉，请先登录。'}
 Tue, 11 Jun 2019 20:04:37  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:37  ERROR test_api.py test_api [ line:35 ] 断言出错啦，期望结果为：20109，实际结果为：None
Traceback (most recent call last):
  File "E:\test study\project_2\QCD_API\test_case\test_api.py", line 32, in test_api
    self.assertEqual(eval(res.json()['code']),args['expected'])
TypeError: eval() arg 1 must be a string, bytes or code object
 Tue, 11 Jun 2019 20:04:37  INFO test_api.py test_api [ line:23 ] 正在执行第19条用例
 Tue, 11 Jun 2019 20:04:37  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 19, 'func': 'recharge', 'describe': '输入金额的小数超过2位', 'method': 'post', 'apiName': '/member/recharge', 'param': "{'mobilephone':'13311111111','amount':'5000.012'}", 'expected': 20116}
 Tue, 11 Jun 2019 20:04:37  INFO http_request.py http_request [ line:21 ] 发起post请求
 Tue, 11 Jun 2019 20:04:37  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': None, 'data': None, 'msg': '抱歉，请先登录。'}
 Tue, 11 Jun 2019 20:04:37  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:37  ERROR test_api.py test_api [ line:35 ] 断言出错啦，期望结果为：20116，实际结果为：None
Traceback (most recent call last):
  File "E:\test study\project_2\QCD_API\test_case\test_api.py", line 32, in test_api
    self.assertEqual(eval(res.json()['code']),args['expected'])
TypeError: eval() arg 1 must be a string, bytes or code object
 Tue, 11 Jun 2019 20:04:37  INFO test_api.py test_api [ line:23 ] 正在执行第20条用例
 Tue, 11 Jun 2019 20:04:37  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 20, 'func': 'recharge', 'describe': '充值金额输入负数', 'method': 'post', 'apiName': '/member/recharge', 'param': "{'mobilephone':'13311111111','amount':'-5000'}", 'expected': 20117}
 Tue, 11 Jun 2019 20:04:37  INFO http_request.py http_request [ line:21 ] 发起post请求
 Tue, 11 Jun 2019 20:04:37  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': None, 'data': None, 'msg': '抱歉，请先登录。'}
 Tue, 11 Jun 2019 20:04:37  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:37  ERROR test_api.py test_api [ line:35 ] 断言出错啦，期望结果为：20117，实际结果为：None
Traceback (most recent call last):
  File "E:\test study\project_2\QCD_API\test_case\test_api.py", line 32, in test_api
    self.assertEqual(eval(res.json()['code']),args['expected'])
TypeError: eval() arg 1 must be a string, bytes or code object
 Tue, 11 Jun 2019 20:04:37  INFO test_api.py test_api [ line:23 ] 正在执行第21条用例
 Tue, 11 Jun 2019 20:04:37  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 21, 'func': 'recharge', 'describe': '充值金额输入超过50万', 'method': 'post', 'apiName': '/member/recharge', 'param': "{'mobilephone':'13311111111','amount':'5000000'}", 'expected': 20117}
 Tue, 11 Jun 2019 20:04:37  INFO http_request.py http_request [ line:21 ] 发起post请求
 Tue, 11 Jun 2019 20:04:38  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': None, 'data': None, 'msg': '抱歉，请先登录。'}
 Tue, 11 Jun 2019 20:04:38  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:38  ERROR test_api.py test_api [ line:35 ] 断言出错啦，期望结果为：20117，实际结果为：None
Traceback (most recent call last):
  File "E:\test study\project_2\QCD_API\test_case\test_api.py", line 32, in test_api
    self.assertEqual(eval(res.json()['code']),args['expected'])
TypeError: eval() arg 1 must be a string, bytes or code object
 Tue, 11 Jun 2019 20:04:38  INFO test_api.py test_api [ line:23 ] 正在执行第22条用例
 Tue, 11 Jun 2019 20:04:38  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 22, 'func': 'recharge', 'describe': '输入金额为非数字', 'method': 'post', 'apiName': '/member/recharge', 'param': "{'mobilephone':'13311111111','amount':'we'}", 'expected': 20118}
 Tue, 11 Jun 2019 20:04:38  INFO http_request.py http_request [ line:21 ] 发起post请求
 Tue, 11 Jun 2019 20:04:38  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': None, 'data': None, 'msg': '抱歉，请先登录。'}
 Tue, 11 Jun 2019 20:04:38  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:38  ERROR test_api.py test_api [ line:35 ] 断言出错啦，期望结果为：20118，实际结果为：None
Traceback (most recent call last):
  File "E:\test study\project_2\QCD_API\test_case\test_api.py", line 32, in test_api
    self.assertEqual(eval(res.json()['code']),args['expected'])
TypeError: eval() arg 1 must be a string, bytes or code object
 Tue, 11 Jun 2019 20:04:38  INFO test_api.py test_api [ line:23 ] 正在执行第23条用例
 Tue, 11 Jun 2019 20:04:38  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 23, 'func': 'withdraw', 'describe': '取现成功', 'method': 'post', 'apiName': '/member/withdraw', 'param': "{'mobilephone':'13311111111','amount':'500'}", 'expected': 10001}
 Tue, 11 Jun 2019 20:04:38  INFO http_request.py http_request [ line:21 ] 发起post请求
 Tue, 11 Jun 2019 20:04:38  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': None, 'data': None, 'msg': '抱歉，请先登录。'}
 Tue, 11 Jun 2019 20:04:38  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:38  ERROR test_api.py test_api [ line:35 ] 断言出错啦，期望结果为：10001，实际结果为：None
Traceback (most recent call last):
  File "E:\test study\project_2\QCD_API\test_case\test_api.py", line 32, in test_api
    self.assertEqual(eval(res.json()['code']),args['expected'])
TypeError: eval() arg 1 must be a string, bytes or code object
 Tue, 11 Jun 2019 20:04:38  INFO test_api.py test_api [ line:23 ] 正在执行第24条用例
 Tue, 11 Jun 2019 20:04:38  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 24, 'func': 'withdraw', 'describe': '取现时未输入金额', 'method': 'post', 'apiName': '/member/withdraw', 'param': "{'mobilephone':'13311111111','amount':''}", 'expected': 20115}
 Tue, 11 Jun 2019 20:04:38  INFO http_request.py http_request [ line:21 ] 发起post请求
 Tue, 11 Jun 2019 20:04:38  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': None, 'data': None, 'msg': '抱歉，请先登录。'}
 Tue, 11 Jun 2019 20:04:38  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:38  ERROR test_api.py test_api [ line:35 ] 断言出错啦，期望结果为：20115，实际结果为：None
Traceback (most recent call last):
  File "E:\test study\project_2\QCD_API\test_case\test_api.py", line 32, in test_api
    self.assertEqual(eval(res.json()['code']),args['expected'])
TypeError: eval() arg 1 must be a string, bytes or code object
 Tue, 11 Jun 2019 20:04:38  INFO test_api.py test_api [ line:23 ] 正在执行第25条用例
 Tue, 11 Jun 2019 20:04:38  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 25, 'func': 'withdraw', 'describe': '不输入手机号', 'method': 'post', 'apiName': '/member/withdraw', 'param': "{'mobilephone':'','amount':'500'}", 'expected': 20103}
 Tue, 11 Jun 2019 20:04:38  INFO http_request.py http_request [ line:21 ] 发起post请求
 Tue, 11 Jun 2019 20:04:38  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': None, 'data': None, 'msg': '抱歉，请先登录。'}
 Tue, 11 Jun 2019 20:04:38  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:38  ERROR test_api.py test_api [ line:35 ] 断言出错啦，期望结果为：20103，实际结果为：None
Traceback (most recent call last):
  File "E:\test study\project_2\QCD_API\test_case\test_api.py", line 32, in test_api
    self.assertEqual(eval(res.json()['code']),args['expected'])
TypeError: eval() arg 1 must be a string, bytes or code object
 Tue, 11 Jun 2019 20:04:38  INFO test_api.py test_api [ line:23 ] 正在执行第26条用例
 Tue, 11 Jun 2019 20:04:38  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 26, 'func': 'withdraw', 'describe': '不存在的会员手机账号', 'method': 'post', 'apiName': '/member/withdraw', 'param': "{'mobilephone':'13322111111','amount':'500'}", 'expected': 20104}
 Tue, 11 Jun 2019 20:04:38  INFO http_request.py http_request [ line:21 ] 发起post请求
 Tue, 11 Jun 2019 20:04:38  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': None, 'data': None, 'msg': '抱歉，请先登录。'}
 Tue, 11 Jun 2019 20:04:38  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:38  ERROR test_api.py test_api [ line:35 ] 断言出错啦，期望结果为：20104，实际结果为：None
Traceback (most recent call last):
  File "E:\test study\project_2\QCD_API\test_case\test_api.py", line 32, in test_api
    self.assertEqual(eval(res.json()['code']),args['expected'])
TypeError: eval() arg 1 must be a string, bytes or code object
 Tue, 11 Jun 2019 20:04:38  INFO test_api.py test_api [ line:23 ] 正在执行第27条用例
 Tue, 11 Jun 2019 20:04:38  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 27, 'func': 'withdraw', 'describe': '手机格式不正确', 'method': 'post', 'apiName': '/member/withdraw', 'param': "{'mobilephone':'1331111','amount':'500'}", 'expected': 20109}
 Tue, 11 Jun 2019 20:04:38  INFO http_request.py http_request [ line:21 ] 发起post请求
 Tue, 11 Jun 2019 20:04:39  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': None, 'data': None, 'msg': '抱歉，请先登录。'}
 Tue, 11 Jun 2019 20:04:39  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:39  ERROR test_api.py test_api [ line:35 ] 断言出错啦，期望结果为：20109，实际结果为：None
Traceback (most recent call last):
  File "E:\test study\project_2\QCD_API\test_case\test_api.py", line 32, in test_api
    self.assertEqual(eval(res.json()['code']),args['expected'])
TypeError: eval() arg 1 must be a string, bytes or code object
 Tue, 11 Jun 2019 20:04:39  INFO test_api.py test_api [ line:23 ] 正在执行第28条用例
 Tue, 11 Jun 2019 20:04:39  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 28, 'func': 'withdraw', 'describe': '输入金额的小数超过2位', 'method': 'post', 'apiName': '/member/withdraw', 'param': "{'mobilephone':'13311111111','amount':'500.012'}", 'expected': 20116}
 Tue, 11 Jun 2019 20:04:39  INFO http_request.py http_request [ line:21 ] 发起post请求
 Tue, 11 Jun 2019 20:04:39  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': None, 'data': None, 'msg': '抱歉，请先登录。'}
 Tue, 11 Jun 2019 20:04:39  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:39  ERROR test_api.py test_api [ line:35 ] 断言出错啦，期望结果为：20116，实际结果为：None
Traceback (most recent call last):
  File "E:\test study\project_2\QCD_API\test_case\test_api.py", line 32, in test_api
    self.assertEqual(eval(res.json()['code']),args['expected'])
TypeError: eval() arg 1 must be a string, bytes or code object
 Tue, 11 Jun 2019 20:04:39  INFO test_api.py test_api [ line:23 ] 正在执行第29条用例
 Tue, 11 Jun 2019 20:04:39  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 29, 'func': 'withdraw', 'describe': '取现金额输入负数', 'method': 'post', 'apiName': '/member/withdraw', 'param': "{'mobilephone':'13311111111','amount':'-500'}", 'expected': 20117}
 Tue, 11 Jun 2019 20:04:39  INFO http_request.py http_request [ line:21 ] 发起post请求
 Tue, 11 Jun 2019 20:04:39  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': None, 'data': None, 'msg': '抱歉，请先登录。'}
 Tue, 11 Jun 2019 20:04:39  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:39  ERROR test_api.py test_api [ line:35 ] 断言出错啦，期望结果为：20117，实际结果为：None
Traceback (most recent call last):
  File "E:\test study\project_2\QCD_API\test_case\test_api.py", line 32, in test_api
    self.assertEqual(eval(res.json()['code']),args['expected'])
TypeError: eval() arg 1 must be a string, bytes or code object
 Tue, 11 Jun 2019 20:04:39  INFO test_api.py test_api [ line:23 ] 正在执行第30条用例
 Tue, 11 Jun 2019 20:04:39  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 30, 'func': 'withdraw', 'describe': '取现金额输入超过50万', 'method': 'post', 'apiName': '/member/withdraw', 'param': "{'mobilephone':'13311111111','amount':'5000000'}", 'expected': 20117}
 Tue, 11 Jun 2019 20:04:39  INFO http_request.py http_request [ line:21 ] 发起post请求
 Tue, 11 Jun 2019 20:04:39  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': None, 'data': None, 'msg': '抱歉，请先登录。'}
 Tue, 11 Jun 2019 20:04:39  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:39  ERROR test_api.py test_api [ line:35 ] 断言出错啦，期望结果为：20117，实际结果为：None
Traceback (most recent call last):
  File "E:\test study\project_2\QCD_API\test_case\test_api.py", line 32, in test_api
    self.assertEqual(eval(res.json()['code']),args['expected'])
TypeError: eval() arg 1 must be a string, bytes or code object
 Tue, 11 Jun 2019 20:04:39  INFO test_api.py test_api [ line:23 ] 正在执行第31条用例
 Tue, 11 Jun 2019 20:04:39  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 31, 'func': 'withdraw', 'describe': '输入金额为非数字', 'method': 'post', 'apiName': '/member/withdraw', 'param': "{'mobilephone':'13311111111','amount':'we'}", 'expected': 20118}
 Tue, 11 Jun 2019 20:04:39  INFO http_request.py http_request [ line:21 ] 发起post请求
 Tue, 11 Jun 2019 20:04:39  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': None, 'data': None, 'msg': '抱歉，请先登录。'}
 Tue, 11 Jun 2019 20:04:39  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:39  ERROR test_api.py test_api [ line:35 ] 断言出错啦，期望结果为：20118，实际结果为：None
Traceback (most recent call last):
  File "E:\test study\project_2\QCD_API\test_case\test_api.py", line 32, in test_api
    self.assertEqual(eval(res.json()['code']),args['expected'])
TypeError: eval() arg 1 must be a string, bytes or code object
 Tue, 11 Jun 2019 20:04:39  INFO test_api.py test_api [ line:23 ] 正在执行第32条用例
 Tue, 11 Jun 2019 20:04:39  INFO test_api.py test_api [ line:24 ] 测试参数：{'case_id': 32, 'func': 'withdraw', 'describe': '输入金额大于账户余额', 'method': 'post', 'apiName': '/member/withdraw', 'param': "{'mobilephone':'13311111111','amount':'6000'}", 'expected': 20119}
 Tue, 11 Jun 2019 20:04:39  INFO http_request.py http_request [ line:21 ] 发起post请求
 Tue, 11 Jun 2019 20:04:39  INFO test_api.py test_api [ line:28 ] 返回结果：{'status': 0, 'code': None, 'data': None, 'msg': '抱歉，请先登录。'}
 Tue, 11 Jun 2019 20:04:39  INFO test_api.py test_api [ line:29 ] <class 'int'>
 Tue, 11 Jun 2019 20:04:39  ERROR test_api.py test_api [ line:35 ] 断言出错啦，期望结果为：20119，实际结果为：None
Traceback (most recent call last):
  File "E:\test study\project_2\QCD_API\test_case\test_api.py", line 32, in test_api
    self.assertEqual(eval(res.json()['code']),args['expected'])
TypeError: eval() arg 1 must be a string, bytes or code object
